quest: Quest Device {
	happlay: Tacton Player App (c++ NDK, openxr+vulkan)\nNo GUI at all currently, can be used headless
}
touchpro: Touch Pro Controllers
quest.happlay <-> touchpro: Tacton Playback

pc: PC {
	browser: Browser {
		controlwapp: Control Web App
	}

	server: Persistent Coordinating Server (nodejs)\nsupports multiple devices/controllers

	browser.controlwapp <-> server: Websocket
}
pc.server <-> quest.happlay: Websocket

pc.server <-> ngrok: (tunnel, allows 0 effort firewall bypass) {
	style.stroke-dash: 5
}
ngrok <-> quest.happlay: (tunnel, constant domain so no\ntyping IPs in the headset) {
	style.stroke-dash: 5
}



