name: Build APK

on:
  push:
    branches: [ main, testactions ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
          cmdline-tools-version: 11076708

      - name: Setup local.properties
        run: echo -e "sdk.dir=$ANDROID_SDK_ROOT\nWS_SERVER_DOMAIN=happbserver.local\nWS_SERVER_PORT=8080" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: questxr-happlay-app-debug
          path: app/build/outputs/apk/debug/
